/*****
 * 
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

 * 
 * */

public class Q389_Find_the_Difference {
	// time is O(n)
	public char findDifferent(String s, String t){
		int[] hash1 = new int[256];
		int[] hash2 = new int[256];
		
		for(char c : s.toCharArray()){
			hash1[c]++;
		}
		
		for(char c : t.toCharArray()){
			hash2[c]++;
		}
		
		for(int i = 0; i < 256; i++){
			if(hash1[i] != hash2[i]){
				return (char) (i);
			}
		}
		
		return ' ';
	}
}
